In [1]:
%pip install numpy pandas

Requirement already satisfied: numpy in c:\users\sunnykumar.bhakta\sunny-dev\conepts\signle\notebook\myenv\lib\site-packages (2.4.4)
Requirement already satisfied: pandas in c:\users\sunnykumar.bhakta\sunny-dev\conepts\signle\notebook\myenv\lib\site-packages (3.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sunnykumar.bhakta\sunny-dev\conepts\signle\notebook\myenv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\sunnykumar.bhakta\sunny-dev\conepts\signle\notebook\myenv\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\sunnykumar.bhakta\sunny-dev\conepts\signle\notebook\myenv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~lotly (C:\Users\sunnykumar.bhakta\sunny-dev\conepts\signle\notebook\myenv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~lotly (C:\Users\sunnykumar.bhakta\sunny-dev\conepts\signle\notebook\myenv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~lotly (C:\Users\sunnykumar.bhakta\sunny-dev\conepts\signle\notebook\myenv\Lib\site-packages)

[notice] A new release of pip is available: 24.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [65]:
import numpy as np 
import pandas as pd 
from rich import print

In [36]:
data_dict = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

#### Creating a DataFrame

In [46]:
df = pd.DataFrame(data_dict)

In [48]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [6]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

In [73]:
df1 = pd.DataFrame(data_list)
df1

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [74]:
df1[[1, 2]] # incase of column as index 0,1 ,2 we can use use it to extract column based on it

    1         2
0  28  New York
1  34     Paris
2  29    Berlin
3  42    London

In [70]:
df2 = pd.DataFrame(data_list, columns=columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [72]:
df2[["Name", "City"]] # as we added label to column so index won;t work need to use Coumn Name

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [86]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

#### Adding new column

In [88]:
df2["Designaition"] = ["Doctor", "Eng", "Mechanic", "Scienticts"]
df2

    Name  Age      City  Salary Designaition
0   John   28  New York   65000       Doctor
1   Anna   34     Paris   70000          Eng
2  Peter   29    Berlin   62000     Mechanic
3  Linda   42    London   85000   Scienticts

#### Removing rows

In [90]:
df2.drop([0, 1], axis=0)

    Name  Age    City  Salary Designaition
2  Peter   29  Berlin   62000     Mechanic
3  Linda   42  London   85000   Scienticts

#### Remove Columns

In [91]:
df2.drop(["Age", "Salary"], axis=1)

    Name      City Designaition
0   John  New York       Doctor
1   Anna     Paris          Eng
2  Peter    Berlin     Mechanic
3  Linda    London   Scienticts

#### Select row

In [92]:
df2.loc[[0,1]] # loc called location, used when index is number like 0, 1, 2

   Name  Age      City  Salary Designaition
0  John   28  New York   65000       Doctor
1  Anna   34     Paris   70000          Eng

In [93]:
df2

    Name  Age      City  Salary Designaition
0   John   28  New York   65000       Doctor
1   Anna   34     Paris   70000          Eng
2  Peter   29    Berlin   62000     Mechanic
3  Linda   42    London   85000   Scienticts

In [96]:
df2.iloc[[2, 3]] ## index loc called location, used when index is diff then number like 0, 1, 2

    Name  Age    City  Salary Designaition
2  Peter   29  Berlin   62000     Mechanic
3  Linda   42  London   85000   Scienticts

In [97]:
df2

    Name  Age      City  Salary Designaition
0   John   28  New York   65000       Doctor
1   Anna   34     Paris   70000          Eng
2  Peter   29    Berlin   62000     Mechanic
3  Linda   42    London   85000   Scienticts

#### Creating subset

In [98]:
df2.loc[[0,1], ["City","Name", "Age"]]

       City  Name  Age
0  New York  John   28
1     Paris  Anna   34

In [29]:
df2.loc[[2, 3]][["Name", "Age"]]

    Name  Age
2  Peter   29
3  Linda   42

#### Conditional Selection

In [99]:
df2

    Name  Age      City  Salary Designaition
0   John   28  New York   65000       Doctor
1   Anna   34     Paris   70000          Eng
2  Peter   29    Berlin   62000     Mechanic
3  Linda   42    London   85000   Scienticts

In [100]:
df2[df2["Age"] <30]

    Name  Age      City  Salary Designaition
0   John   28  New York   65000       Doctor
2  Peter   29    Berlin   62000     Mechanic

In [101]:
df2[(df2["Age"] <30) & (df2["Designaition"]=="Doctor")]

   Name  Age      City  Salary Designaition
0  John   28  New York   65000       Doctor