In [3]:
%pip install numpy pandas

Requirement already satisfied: numpy in c:\users\sunnykumar.bhakta\sunny-dev\conepts\signle\notebook\myenv\lib\site-packages (2.4.4)
Requirement already satisfied: pandas in c:\users\sunnykumar.bhakta\sunny-dev\conepts\signle\notebook\myenv\lib\site-packages (3.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sunnykumar.bhakta\sunny-dev\conepts\signle\notebook\myenv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\sunnykumar.bhakta\sunny-dev\conepts\signle\notebook\myenv\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\sunnykumar.bhakta\sunny-dev\conepts\signle\notebook\myenv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import numpy as np 
import pandas as pd

In [4]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

In [5]:
df = pd.DataFrame(data)

In [6]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [9]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

In [12]:
pd.DataFrame(data_list)

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [13]:
columns=['Name', "Age", "City", "Salary"]
df2 = pd.DataFrame(data_list, columns=columns)

In [14]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [15]:
df2[["Name", "Age"]]

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [16]:
df2["Designaition"] = ["Doctor", "Eng", "Mechanic", "Scienticts"]

In [17]:
df2

    Name  Age      City  Salary Designaition
0   John   28  New York   65000       Doctor
1   Anna   34     Paris   70000          Eng
2  Peter   29    Berlin   62000     Mechanic
3  Linda   42    London   85000   Scienticts

## Removing rows

In [18]:
df2.drop(0, axis=0)

    Name  Age    City  Salary Designaition
1   Anna   34   Paris   70000          Eng
2  Peter   29  Berlin   62000     Mechanic
3  Linda   42  London   85000   Scienticts

In [19]:
df2

    Name  Age      City  Salary Designaition
0   John   28  New York   65000       Doctor
1   Anna   34     Paris   70000          Eng
2  Peter   29    Berlin   62000     Mechanic
3  Linda   42    London   85000   Scienticts

## Remoce Columns

In [23]:
df2.drop(["Age", "Designaition"], axis=1)

    Name      City  Salary
0   John  New York   65000
1   Anna     Paris   70000
2  Peter    Berlin   62000
3  Linda    London   85000

In [24]:
df2.loc[[0,1]]

   Name  Age      City  Salary Designaition
0  John   28  New York   65000       Doctor
1  Anna   34     Paris   70000          Eng

In [25]:
df2

    Name  Age      City  Salary Designaition
0   John   28  New York   65000       Doctor
1   Anna   34     Paris   70000          Eng
2  Peter   29    Berlin   62000     Mechanic
3  Linda   42    London   85000   Scienticts

In [26]:
df2.iloc[3]

Name                 Linda
Age                     42
City                London
Salary               85000
Designaition    Scienticts
Name: 3, dtype: object

In [27]:
df2

    Name  Age      City  Salary Designaition
0   John   28  New York   65000       Doctor
1   Anna   34     Paris   70000          Eng
2  Peter   29    Berlin   62000     Mechanic
3  Linda   42    London   85000   Scienticts

In [32]:
df2.loc[[0,1], ["City","Name", "Age"]]

       City  Name  Age
0  New York  John   28
1     Paris  Anna   34

## Conditional Selection

In [33]:
df2

    Name  Age      City  Salary Designaition
0   John   28  New York   65000       Doctor
1   Anna   34     Paris   70000          Eng
2  Peter   29    Berlin   62000     Mechanic
3  Linda   42    London   85000   Scienticts

In [34]:
df2[df2["Age"] <30]

    Name  Age      City  Salary Designaition
0   John   28  New York   65000       Doctor
2  Peter   29    Berlin   62000     Mechanic

In [36]:
df2[(df2["Age"] <30) & (df2["Designaition"]=="Doctor")]

   Name  Age      City  Salary Designaition
0  John   28  New York   65000       Doctor