In [1]:
import numpy as np 
import pandas as pd

In [2]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

In [3]:
df

         Date Product Region  Sales  Units    Rep
0  2023-01-01       A   East    375     88   John
1  2023-01-02       B   West    851     44   Mary
2  2023-01-03       C  North    770     94    Bob
3  2023-01-04       D  South    517     87  Alice
4  2023-01-05       A   East    963     64   John
5  2023-01-06       B   West    481     54   Mary
6  2023-01-07       C  North    974     11    Bob
7  2023-01-08       D  South    900     12  Alice
8  2023-01-09       A   East    232     60   John
9  2023-01-10       B   West    602     14   Mary
10 2023-01-11       C  North    862     10    Bob
11 2023-01-12       D  South    250     17  Alice
12 2023-01-13       A   East    472     26   John
13 2023-01-14       B   West    500     67   Mary
14 2023-01-15       C  North    144     57    Bob
15 2023-01-16       D  South    254     71  Alice
16 2023-01-17       A   East    212     89   John
17 2023-01-18       B   West    163     77   Mary
18 2023-01-19       C  North    947     80    Bob
19 2023-01-20       D  South    808     64  Alice

In [4]:
df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)

In [5]:
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    375     88   John  January      Q1
1  2023-01-02       B   West    851     44   Mary  January      Q1
2  2023-01-03       C  North    770     94    Bob  January      Q1
3  2023-01-04       D  South    517     87  Alice  January      Q1
4  2023-01-05       A   East    963     64   John  January      Q1
5  2023-01-06       B   West    481     54   Mary  January      Q1
6  2023-01-07       C  North    974     11    Bob  January      Q1
7  2023-01-08       D  South    900     12  Alice  January      Q1
8  2023-01-09       A   East    232     60   John  January      Q1
9  2023-01-10       B   West    602     14   Mary  January      Q1
10 2023-01-11       C  North    862     10    Bob  January      Q1
11 2023-01-12       D  South    250     17  Alice  January      Q1
12 2023-01-13       A   East    472     26   John  January      Q1
13 2023-01-14       B   West    500     67   Mary  January      Q1
14 2023-01-15       C  North    144     57    Bob  January      Q1
15 2023-01-16       D  South    254     71  Alice  January      Q1
16 2023-01-17       A   East    212     89   John  January      Q1
17 2023-01-18       B   West    163     77   Mary  January      Q1
18 2023-01-19       C  North    947     80    Bob  January      Q1
19 2023-01-20       D  South    808     64  Alice  January      Q1

In [6]:
pd.pivot_table(df,values = "Sales",index = 'Region',columns="Product",aggfunc = 'mean') # Default mean

Product      A      B      C      D
Region
East     450.8    NaN    NaN    NaN
North      NaN    NaN  739.4    NaN
South      NaN    NaN    NaN  545.8
West       NaN  519.4    NaN    NaN

In [7]:
pd.pivot_table(df,values = "Sales",index = 'Region',columns="Product",aggfunc = 'median')

Product      A      B      C      D
Region
East     375.0    NaN    NaN    NaN
North      NaN    NaN  862.0    NaN
South      NaN    NaN    NaN  517.0
West       NaN  500.0    NaN    NaN

In [8]:
pivot2 = pd.pivot_table(df, values=['Sales', 'Units'], index='Region', columns='Product')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     450.8    NaN    NaN    NaN  65.4   NaN   NaN   NaN
North      NaN    NaN  739.4    NaN   NaN   NaN  50.4   NaN
South      NaN    NaN    NaN  545.8   NaN   NaN   NaN  50.2
West       NaN  519.4    NaN    NaN   NaN  51.2   NaN   NaN

## Cross Tabs

In [9]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0