In [31]:
import numpy as np 
import pandas as pd 
import re
from datetime import datetime

In [11]:
print(1)
df = pd.read_csv("08_Feature_Extraction.csv")
print(2)

1
2

df.shape

In [13]:
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [12]:
df.loc[4]['Title']

'Shingeki no Kyojin Season 3 Part 2TV (10 eps)Apr 2019 - Jul 20192,146,679 membersManga StoreVolume 1€10.99Preview'

In [25]:
df["Episode"] = df["Title"].apply(lambda txt: re.search(r'(\d+)\s*eps', txt).group(1))

In [19]:
df.head

   Rank                                              Title  Score Episode
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10      64
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07      24
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06      13
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06      51
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05      10

In [23]:
type(df["Episode"][0])

str

In [26]:
df["Episode"] = df["Episode"].astype(int)
type(df["Episode"][0])

numpy.int64

- make a new column for episode count
- make a new column for time stamp
- which anime has the highest score
- give me top 5 highest scoring anime
- which anime has the highest episode count
- animes with top 5 episode count
- which is the longest running anime

In [28]:
df.loc[3]["Title"]

'Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members'

In [29]:
df["Total_Time"] = df["Title"].apply(lambda text : re.search(r'[A-Za-z]{3}\s\d{4}\s-\s[A-Za-z]{3}\s\d{4}', text).group())

In [30]:
df.head()

,Rank,Title,Score,Episode,Total_Time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

In [33]:
def calculate_months(text):
    # Split dates
    start_str, end_str = text.split(" - ")
    
    # Convert to datetime
    start = datetime.strptime(start_str, "%b %Y")
    end = datetime.strptime(end_str, "%b %Y")
    
    # Calculate total months
    months = (end.year - start.year) * 12 + (end.month - start.month)
    return months

In [34]:
df["Months"] = df["Total_Time"].apply(calculate_months)

In [35]:
df.head()

,Rank,Title,Score,Episode,Total_Time,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,15
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,5
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,2
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,11
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,3

In [36]:
df[df['Score'] == df['Score'].max()]['Title']

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
Name: Title, dtype: str

In [38]:
df[df['Episode'] == df['Episode'].max()]

,Rank,Title,Score,Episode,Total_Time,Months
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,47